; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio] ; Global Parameters
description = "Hello World Example"

[env]
platform = native ; Software for host computer
build_flags = -O0
    -std=c11 ; Standart of C lang
    -Wall ; Display all Warnings
test_framework = custom

[env:helloworld] ; Working environment for 'hello world' programm
build_type = debug ; Enable debug symbols
build_src_filter = +<helloworld/*.c> ; Source files directory ./src/helloworld
debug_test = native/test_dynlist
check_tool = cppcheck
check_flags = cppcheck:--enable=all
    --suppress=unusedFunction
    --suppress=unmatchedSuppression
check_src_filters =
    +<src/helloworld/*.c>
    +<lib/dynlist/src/*.c>