[platformio] 
    description = "template project with stm32cube"
    default_envs = bootloader

; глобальные и общие параметры
[env]
platform = ststm32
board = nucleo_h745zi_q
framework = stm32cube
build_flags = -std=c11 -Wall -Wextra -D CORE_CM7 -D HSE_VALUE=8000000 -D USE_FULL_ASSERT -D USE_CUSTOM_ASSSERTIONS
monitor_speed = 115200
test_speed = 115200
test_filter = target/*
test_framework = custom ; использовать test_custom_runner.py в папке test
check_tool = cppcheck
check_flags = cppcheck:--enable=all --suppress=unusedFunction  
build_type = debug
debug_init_cmds = target extended-remote $DEBUG_PORT
                $LOAD_CMDS 
                $INIT_BREAK

board_build.stm32cube.custom_config_header = yes ; использовать свой stm32h7xx_hal_conf.h

; основное приложение, запуск из AXI-SRAM, исходн.коды в src/app/*                  
[env:cm7app_in_ram] 
build_src_filter =  +<cm7app/*.c> 
check_src_filters = +<src/cm7app/*.c>
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_sram1_CM7.ld
build_flags = ${env.build_flags} -D CORE_CM7 -D VECT_TAB_SRAM -D USER_VECT_TAB_ADDRESS
upload_protocol = custom ;кастомизируем алгоритм загрузки - в RAM, а не во FLASH 
; upload_command задается одной строкой без переносов
upload_command = openocd -f interface/stlink.cfg -f target/stm32h7x_dual_bank.cfg -c "init; halt; load_image .pio/build/cm7app_in_ram/firmware.bin 0x24000000; verify_image .pio/build/cm7app_in_ram/firmware.bin 0x24000000; reset; exit"
 
[env:cm7app_in_flash]
build_src_filter = +<cm7app/*.c>
check_src_filters = +<src/cm7app/*.c>
board_build.ldscript = $PROJECT_DIR/system/STM32H745ZITX_M7_FLASH.ld
build_flags = ${env.build_flags} -D CORE_CM7 

; Рабочее приложение для Cortex-M4, запуск из FLASH BANK-2
[env:cm4app_in_flash]
build_flags = ${env.build_flags} -D CORE_CM4 
check_src_filters = +<src/cm4app/*.c>
build_src_filter = +<cm4app/*.c> 
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_flash_CM4.ld

; Загрузчик, запуск из FLASH BANK-1, позволяет запускать приложение из AXI-SRAM и запускать ядро CM4 
[env:bootloader]
    framework = cmsis
    build_src_filter = +<bootloader/*.c> 
    check_src_filters = +<src/bootloader/*.c>
    board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_flash_CM7.ld
    build_flags = ${env.build_flags} -D CORE_CM7 
