; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = nucleo_h745zi_q
framework = cmsis
test_framework = custom

monitor_speed = 115200
test_speed = 115200

build_flags = 
    -std=c11 
    -Wall 
    -Wextra 
    -D CORE_CM7
    -D USE_PWR_DIRECT_SMPS_SUPPLY 

board_build.cmsis.startup_file = broken_path
board_build.cmsis.system_file = broken_path

lib_deps = throwtheswitch/Unity@^2.6.1

debug_init_cmds = target extended-remote $DEBUG_PORT $LOAD_CMDS $INIT_BREAK

[env:blinker_flash]
build_src_filter =
    +<$PROJECT_DIR/system/*.c>
    +<$PROJECT_DIR/system/*.s>
    +<blinker/*.c>
board_build.ldscript = $PROJECT_DIR/system/h745cm7_flash.ld

[env:blinker_ram]
build_src_filter =
    +<$PROJECT_DIR/system/*.c>
    +<$PROJECT_DIR/system/*.s>
    +<blinker/*.c>

build_flags = 
    ${env.build_flags}
    -D VECT_TAB_SRAM
    ; -D USER_VECT_TAB_ADDRESS
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_sram1_CM7.ld

[env:bootloader]
build_src_filter =
    +<$PROJECT_DIR/system/*.c>
    +<$PROJECT_DIR/system/*.s>
    +<bootloader/*.c>
board_build.ldscript = $PROJECT_DIR/system/h745cm7_flash.ld
