; Инструкция по работе с проектом
;
; ВАРИАНТ 1 - РЕКОМЕНДОВАННЫЙ
;   1. Проверить прошит ли загрузчик: Если после сброса или подключения плат на светодиодах бегущий огонь, то прошит.
;   2. Если загрузчик не прошит, то выбрать окружение bootloader и прошить (кнопка -> в панели состояния)
;   3. Далее выбираете окружение cm7app_in_ram:
;       - запускать отладку (F5)  
;       - запускать без отладки (кнопка -> в панели состояния) - программа запустится автоматически через 5 секунд
;   ВАЖНО: Функцию main() начинать с   __enable_irq(); 
;
; ВАРИАНТ 2 - ЕСЛИ ВАРИАНТ 1 НЕ РАБОТАЕТ 
;   1. Выбираете окружение cm7app_in_fash:
;       - запускать отладку (F5)  
;       - запускать без отладки (кнопка -> в панели состояния) - программа запустится автоматически через 5 секунд
;
; ЕСЛИ НЕ ПРОИШВАЕТСЯ ЗАГРЗУЧИК/ПРОГРАММА cm7app_in_flash
;   1. Удерживайте синию кнопку, а затем нажимаете RESET, но синию кнопку держите
;   2. Прошиваете 
;   3  Отпускаете синию кнопку
;   

[platformio] 
    description = "template project with stm32cube"
    default_envs = cm7app_in_ram

; глобальные и общие параметры
[env]
platform = ststm32
board = nucleo_h745zi_q
framework = stm32cube
board_build.stm32cube.custom_system_setup = yes  ; используем свое starup файлы из папки system
board_build.stm32cube.custom_config_header = yes ; использщовать свой stm32h7xx_hal_conf.h
monitor_speed = 115200
test_speed = 115200
test_filter = target/*
test_framework = custom ; использовать test_custom_runner.py в папке test
check_tool = cppcheck
check_flags = cppcheck:--enable=all --suppress=unusedFunction  
build_type = debug
debug_init_cmds = target extended-remote $DEBUG_PORT
                $LOAD_CMDS 
                $INIT_BREAK
build_flags = -std=c11 -Wall -Wextra 
    -D PWR_DIRECT_SMPS_SUPPLY -D HSE_VALUE=8000000 -D USE_FULL_ASSERT

    
; основное приложение, размещение в AXI-SRAM, исходн.коды в src/cm7app/*                  
[env:cm7app_in_ram] 
build_src_filter =  +<cm7app/*.c> +<$PROJECT_DIR/system/*>  
check_src_filters = +<src/cm7app/*.c> 
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_sram1_CM7.ld
build_flags = ${env.build_flags} -DCORE_CM7 -DVECT_TAB_SRAM -DUSER_VECT_TAB_ADDRESS
upload_protocol = custom ;кастомизируем алгоритм загрузки - в RAM, а не во FLASH 
; upload_command задается одной строкой без переносов
upload_command = openocd -f interface/stlink.cfg -f target/stm32h7x_dual_bank.cfg -c "init; halt; load_image .pio/build/cm7app_in_ram/firmware.bin 0x24000000; verify_image .pio/build/cm7app_in_ram/firmware.bin 0x24000000; reset; exit"


; основное приложение, размещение во FLASH, исходн.коды в src/cm7app/*        
[env:cm7app_in_flash]
build_src_filter = +<cm7app/*.c> +<$PROJECT_DIR/system/*> 
check_src_filters = +<src/cm7app/*.c> 
board_build.ldscript = $PROJECT_DIR/system/STM32H745ZITX_M7_FLASH.ld
build_flags = ${env.build_flags} -D CORE_CM7 


; Загрузчик, позволяет запускать приложение из AXI-SRAM и запускать ядро CM4 
[env:bootloader]
    framework = cmsis
    board_build.cmsis.startup_file = broken_path
    board_build.cmsis.system_file = broken_path
    build_src_filter = +<bootloader/*.c> +<$PROJECT_DIR/system/*> 
    check_src_filters = +<src/bootloader/*.c> 
    board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_flash_CM7.ld
    build_flags = ${env.build_flags} -D CORE_CM7 
