[platformio] 
description = "шабблон проекта cmsis v.2026.1"
default_envs = app_in_ram

; глобальные и общие параметры
[env]
platform = ststm32
board = nucleo_h745zi_q
framework = cmsis
build_flags = -std=c11 -Wall -Wextra -D CORE_CM7 -D PWR_DIRECT_SMPS_SUPPLY -D HSE_VALUE=8000000
    -D USE_FULL_LL_DRIVER
    -D USE_FULL_ASSERT

board_build.cmsis.startup_file = broken_path
board_build.cmsis.system_file = broken_path
monitor_speed = 115200
test_speed = 115200
test_filter = target/*
test_framework = custom ; использовать test_custom_runner.py в папке test
check_tool = cppcheck
check_flags = cppcheck:--enable=all --suppress=unusedFunction  
check_src_filters = +<src/app/*.c>
build_type = debug
debug_init_cmds = target extended-remote $DEBUG_PORT
                  $LOAD_CMDS 
                  $INIT_BREAK

; основное приложение, запуск из AXI-SRAM, исходн.коды в src/app/*                  
[env:app_in_ram] 
build_src_filter =  +<app/*.c> +<$PROJECT_DIR/system/*>  
                    
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_sram1_CM7.ld
build_flags = ${env.build_flags} -DVECT_TAB_SRAM


                  
; основное приложение, запуск из FLASH, вместо загрузчика
[env:app_in_flash]
build_src_filter = +<app/*.c> +<$PROJECT_DIR/system/*> 
board_build.ldscript = $PROJECT_DIR/system/h745cm7_flash.ld



[env:bootloader]
build_src_filter = +<bootloader/*.c> +<$PROJECT_DIR/system/*>  
board_build.ldscript = $PROJECT_DIR/system/h745cm7_flash.ld
check_src_filters = +<src/bootloader/*.c>